replicaCount: 1

image:
  repository: dtelless/infrastructure-interview-test # You can use the GitHub Registry address here
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

env:
  # Connection settings
  typeormConnection: "mysql"
  typeormHost: "mariadb" # Default to service name, overridden by TF if needed
  typeormPort: "3306"
  typeormUsername: "test"
  typeormDatabase: "test"
  typeormSynchronize: "true"
  
  # Entity settings
  typeormEntities: "dist/entity/*.js"
  typeormSubscribers: "dist/subscriber/*.js"
  typeormMigrations: "dist/migration/*.js"
  typeormEntitiesDir: "dist/entity"
  typeormMigrationsDir: "dist/migration"
  typeormSubscribersDir: "dist/subscriber"

# Secret values should be passed via --set or values file overrides, but we set a default here for structure
secrets:
  typeormPassword: "test"

affinity: {}

topologySpreadConstraints: []
