apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: typeorm-app
spec:
  rules:
  - host: 192.168.32.6.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: typeorm-app
            port:
              number: 3000
