apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "typeorm-app.fullname" . }}-migration
  labels:
    {{- include "typeorm-app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "typeorm-app.fullname" . }}-migration
      labels:
        {{- include "typeorm-app.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migration-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./node_modules/typeorm/cli.js", "migration:run"]
          envFrom:
            - configMapRef:
                name: {{ include "typeorm-app.fullname" . }}-config
            - secretRef:
                name: {{ include "typeorm-app.fullname" . }}-secret
