apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typeorm-app.fullname" . }}-secret
  labels:
    {{- include "typeorm-app.labels" . | nindent 4 }}
type: Opaque
data:
  TYPEORM_PASSWORD: {{ .Values.secrets.typeormPassword | b64enc | quote }}
