name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'infraestructure/charts/typeorm-app/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | helm registry login registry-1.docker.io -u ${{ vars.DOCKER_USERNAME }} --password-stdin

      - name: Package Helm Chart
        run: |
          cd infraestructure/charts/typeorm-app
          helm dependency build
          helm package .

      - name: Push Helm Chart
        run: |
          cd infraestructure/charts/typeorm-app
          # Assuming the version in Chart.yaml is the single source of truth
          CHART_VERSION=$(grep 'version:' Chart.yaml | awk '{print $2}')
          helm push typeorm-app-${CHART_VERSION}.tgz oci://registry-1.docker.io/${{ vars.DOCKER_USERNAME }}/charts
